### ISSUE TITLE
Dont work - Parse TODOs (all files)

### ISSUE THREAD

**Issue by IgorNovozhilov** [kantlove/vscode-todo-parser#54]
vers:
TODO Parser - 1.8.7
VSCode - 1.11.0-insider

Steps:
1. Press F1 > Parse TODOs (all files)
2. Click to "TODO Counter"
3. No reaction
4. Open console:
```
shell.ts:468 Previous work is not finished.: AssertionError: Previous work is not finished.
    at Function.OutputWriter.begin (C:\Users\xxx\.vscode-insiders\extensions\minhthai.vscode-todo-parser-1.8.7\out\src\classes\OutputWriter.js:22:9)
    at C:\Users\xxx\.vscode-insiders\extensions\minhthai.vscode-todo-parser-1.8.7\out\src\types\CommandType.js:15:36
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by peacegiverman** [comment]
I think this happens when there are binary files in the workspace. When `FileReader.readFileLoop()` tries to open a binary file, it returns this error `Detail: File seems to be binary and cannot be opened as text` to the read callback and spoils the whole batch, even if there are valid files in it. This can then result in no todos being parsed and nothing being written to the `OutputWriter`, thus leaving it in an Idle state, instead of Busy which is expected.
